<?php

########################################################################
# Extension Manager/Repository config file for ext: "wt_cart_order"
#
# Auto generated by Extension Builder 2014-01-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Shopping Cart - Order Handler',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Lorenz',
	'author_email' => 'wt_cart_order@extco.de',
	'author_company' => 'extco.de UG (haftungsbeschränkt)',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '2.1.0',
	'constraints' => array(
		'depends' => array(
			'php' => '5.1.0-0.0.0',
			'typo3' => '4.5.0-4.7.99',
			'wt_cart' => '2.1.0',
			'powermail' => '2.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>